//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitasWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario
    {
        public int idHorario { get; set; }
        public string id { get; set; }
        public Nullable<int> idHora { get; set; }
        public string lunes { get; set; }
        public string martes { get; set; }
        public string miercoles { get; set; }
        public string jueves { get; set; }
        public string viernes { get; set; }
        public string sabado { get; set; }
    
        public virtual doctore doctore { get; set; }
        public virtual hora hora { get; set; }
    }
}
